# Generated by Django 4.0 on 2021-12-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medixo_admin', '0002_customer_pharmacy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
