# Generated by Django 4.0 on 2021-12-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_remove_pharmacy_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
