# Generated by Django 4.0 on 2021-12-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0003_pharmacy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
