# Generated by Django 4.0 on 2021-12-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0004_pharmacy_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='country',
            new_name='address',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
