# Generated by Django 4.0 on 2021-12-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0006_rename_address_pharmacy_building_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
