<<<<<<< HEAD
# Generated by Django 4.0 on 2021-12-29 17:57
=======
# Generated by Django 4.0 on 2021-12-29 17:55
>>>>>>> 7ba62cfdc11daecef80eb3625d30697bed52bfce

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='country',
            new_name='building_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='age',
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
<<<<<<< HEAD
=======
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
>>>>>>> 7ba62cfdc11daecef80eb3625d30697bed52bfce
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='street',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='town',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
