# Generated by Django 4.0 on 2021-12-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Doctor', '0002_rename_country_doctor_building_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fathi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
