# Generated by Django 4.0 on 2021-12-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_rename_fathi_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Email Address'),
        ),
    ]
