# Generated by Django 4.0 on 2021-12-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_doctor_gender'),
        ('Doctor', '0005_alter_doctor_email'),
    ]

    operations = [
    ]
