# Generated by Django 4.0 on 2021-12-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_merge_0004_doctor_gender_0005_alter_doctor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
    ]
