# Generated by Django 4.0 on 2022-01-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_remove_doctor_gender_remove_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
