# Generated by Django 4.0 on 2022-01-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_doctor_date_doctor_hour_doctor_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
