# Generated by Django 4.0 on 2022-01-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0009_rename_user_appointment_doctor_id_remove_doctor_date_and_more'),
        ('Doctor', '0011_doctor_speciality'),
    ]

    operations = [
    ]
