# Generated by Django 4.0 on 2022-01-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0012_merge_20220103_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Doctor_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
