# Generated by Django 4.0 on 2022-01-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0014_appointment_clinic_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='img',
            new_name='clinc_img',
        ),
    ]
