# Generated by Django 4.0 on 2022-01-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0012_merge_20220103_1734'),
        ('Doctor', '0014_appointment_clinic_location'),
    ]

    operations = [
    ]
